/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RequestId = IDL.Nat;
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const BookId = IDL.Nat;
export const BookRequest = IDL.Record({
  'id' : RequestId,
  'status' : RequestStatus,
  'bookOwnerId' : UserId,
  'createdAt' : Timestamp,
  'bookId' : BookId,
  'updatedAt' : Timestamp,
  'requesterId' : UserId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BookCondition = IDL.Variant({
  'new' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
});
export const AddBookInput = IDL.Record({
  'title' : IDL.Text,
  'author' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'genre' : IDL.Text,
  'condition' : BookCondition,
});
export const AvailabilityStatus = IDL.Variant({
  'available' : IDL.Null,
  'unavailable' : IDL.Null,
});
export const Book = IDL.Record({
  'id' : BookId,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'author' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'availability' : AvailabilityStatus,
  'genre' : IDL.Text,
  'condition' : BookCondition,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EditBookInput = IDL.Record({
  'title' : IDL.Text,
  'author' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'genre' : IDL.Text,
  'condition' : BookCondition,
});
export const BookWithOwner = IDL.Record({
  'ownerName' : IDL.Text,
  'book' : Book,
});
export const Profile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const ChatId = IDL.Nat;
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'sentAt' : Timestamp,
  'chatId' : ChatId,
  'senderId' : UserId,
});
export const ChatThread = IDL.Record({
  'id' : ChatId,
  'participant1' : UserId,
  'participant2' : UserId,
  'requestId' : RequestId,
  'createdAt' : Timestamp,
});
export const AuthResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const SaveProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const GoogleBookResult = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'publishedDate' : IDL.Text,
  'isbn' : IDL.Text,
  'publisher' : IDL.Text,
  'description' : IDL.Text,
  'authors' : IDL.Vec(IDL.Text),
  'printType' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptBookRequest' : IDL.Func(
      [IDL.Text, RequestId],
      [IDL.Opt(BookRequest)],
      [],
    ),
  'addBook' : IDL.Func([IDL.Text, AddBookInput], [Book], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'declineBookRequest' : IDL.Func(
      [IDL.Text, RequestId],
      [IDL.Opt(BookRequest)],
      [],
    ),
  'deleteBook' : IDL.Func([IDL.Text, BookId], [IDL.Bool], []),
  'editBook' : IDL.Func([IDL.Text, BookId, EditBookInput], [IDL.Opt(Book)], []),
  'getAllAvailableBooks' : IDL.Func([], [IDL.Vec(BookWithOwner)], ['query']),
  'getBookDetail' : IDL.Func([BookId], [IDL.Opt(BookWithOwner)], ['query']),
  'getCallerUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func(
      [IDL.Text, ChatId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'getMyChatThreads' : IDL.Func([IDL.Text], [IDL.Vec(ChatThread)], ['query']),
  'getMyRequestInbox' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
  'getMyRequests' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
  'getOrCreateChatThread' : IDL.Func([IDL.Text, RequestId], [ChatThread], []),
  'getSession' : IDL.Func([IDL.Text], [IDL.Opt(UserId)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, SaveProfileInput], [], []),
  'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(BookWithOwner)], ['query']),
  'searchGoogleBooks' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(GoogleBookResult), 'err' : IDL.Text })],
      [],
    ),
  'sendBookRequest' : IDL.Func([IDL.Text, BookId], [BookRequest], []),
  'sendMessage' : IDL.Func([IDL.Text, ChatId, IDL.Text], [Message], []),
  'setBookAvailability' : IDL.Func(
      [IDL.Text, BookId, AvailabilityStatus],
      [IDL.Opt(Book)],
      [],
    ),
  'signOut' : IDL.Func([IDL.Text], [], []),
  'transformGoogleBooksResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RequestId = IDL.Nat;
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const BookId = IDL.Nat;
  const BookRequest = IDL.Record({
    'id' : RequestId,
    'status' : RequestStatus,
    'bookOwnerId' : UserId,
    'createdAt' : Timestamp,
    'bookId' : BookId,
    'updatedAt' : Timestamp,
    'requesterId' : UserId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BookCondition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
  });
  const AddBookInput = IDL.Record({
    'title' : IDL.Text,
    'author' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'genre' : IDL.Text,
    'condition' : BookCondition,
  });
  const AvailabilityStatus = IDL.Variant({
    'available' : IDL.Null,
    'unavailable' : IDL.Null,
  });
  const Book = IDL.Record({
    'id' : BookId,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'author' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'availability' : AvailabilityStatus,
    'genre' : IDL.Text,
    'condition' : BookCondition,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EditBookInput = IDL.Record({
    'title' : IDL.Text,
    'author' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'genre' : IDL.Text,
    'condition' : BookCondition,
  });
  const BookWithOwner = IDL.Record({ 'ownerName' : IDL.Text, 'book' : Book });
  const Profile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const ChatId = IDL.Nat;
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'sentAt' : Timestamp,
    'chatId' : ChatId,
    'senderId' : UserId,
  });
  const ChatThread = IDL.Record({
    'id' : ChatId,
    'participant1' : UserId,
    'participant2' : UserId,
    'requestId' : RequestId,
    'createdAt' : Timestamp,
  });
  const AuthResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const SaveProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const GoogleBookResult = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'publishedDate' : IDL.Text,
    'isbn' : IDL.Text,
    'publisher' : IDL.Text,
    'description' : IDL.Text,
    'authors' : IDL.Vec(IDL.Text),
    'printType' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptBookRequest' : IDL.Func(
        [IDL.Text, RequestId],
        [IDL.Opt(BookRequest)],
        [],
      ),
    'addBook' : IDL.Func([IDL.Text, AddBookInput], [Book], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'declineBookRequest' : IDL.Func(
        [IDL.Text, RequestId],
        [IDL.Opt(BookRequest)],
        [],
      ),
    'deleteBook' : IDL.Func([IDL.Text, BookId], [IDL.Bool], []),
    'editBook' : IDL.Func(
        [IDL.Text, BookId, EditBookInput],
        [IDL.Opt(Book)],
        [],
      ),
    'getAllAvailableBooks' : IDL.Func([], [IDL.Vec(BookWithOwner)], ['query']),
    'getBookDetail' : IDL.Func([BookId], [IDL.Opt(BookWithOwner)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Profile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func(
        [IDL.Text, ChatId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyBooks' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'getMyChatThreads' : IDL.Func([IDL.Text], [IDL.Vec(ChatThread)], ['query']),
    'getMyRequestInbox' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BookRequest)],
        ['query'],
      ),
    'getMyRequests' : IDL.Func([IDL.Text], [IDL.Vec(BookRequest)], ['query']),
    'getOrCreateChatThread' : IDL.Func([IDL.Text, RequestId], [ChatThread], []),
    'getSession' : IDL.Func([IDL.Text], [IDL.Opt(UserId)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, SaveProfileInput], [], []),
    'searchBooks' : IDL.Func([IDL.Text], [IDL.Vec(BookWithOwner)], ['query']),
    'searchGoogleBooks' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(GoogleBookResult), 'err' : IDL.Text })],
        [],
      ),
    'sendBookRequest' : IDL.Func([IDL.Text, BookId], [BookRequest], []),
    'sendMessage' : IDL.Func([IDL.Text, ChatId, IDL.Text], [Message], []),
    'setBookAvailability' : IDL.Func(
        [IDL.Text, BookId, AvailabilityStatus],
        [IDL.Opt(Book)],
        [],
      ),
    'signOut' : IDL.Func([IDL.Text], [], []),
    'transformGoogleBooksResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };