/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddBookInput {
  'title' : string,
  'author' : string,
  'coverImage' : [] | [ExternalBlob],
  'genre' : string,
  'condition' : BookCondition,
}
export type AuthResult = { 'ok' : string } |
  { 'err' : string };
export type AvailabilityStatus = { 'available' : null } |
  { 'unavailable' : null };
export interface Book {
  'id' : BookId,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'author' : string,
  'coverImage' : [] | [ExternalBlob],
  'availability' : AvailabilityStatus,
  'genre' : string,
  'condition' : BookCondition,
}
export type BookCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null };
export type BookId = bigint;
export interface BookRequest {
  'id' : RequestId,
  'status' : RequestStatus,
  'bookOwnerId' : UserId,
  'createdAt' : Timestamp,
  'bookId' : BookId,
  'updatedAt' : Timestamp,
  'requesterId' : UserId,
}
export interface BookWithOwner { 'ownerName' : string, 'book' : Book }
export type ChatId = bigint;
export interface ChatThread {
  'id' : ChatId,
  'participant1' : UserId,
  'participant2' : UserId,
  'requestId' : RequestId,
  'createdAt' : Timestamp,
}
export interface EditBookInput {
  'title' : string,
  'author' : string,
  'coverImage' : [] | [ExternalBlob],
  'genre' : string,
  'condition' : BookCondition,
}
export type ExternalBlob = Uint8Array;
export interface GoogleBookResult {
  'id' : string,
  'title' : string,
  'thumbnail' : string,
  'publishedDate' : string,
  'isbn' : string,
  'publisher' : string,
  'description' : string,
  'authors' : Array<string>,
  'printType' : string,
}
export interface Message {
  'id' : MessageId,
  'text' : string,
  'sentAt' : Timestamp,
  'chatId' : ChatId,
  'senderId' : UserId,
}
export type MessageId = bigint;
export interface Profile {
  'id' : UserId,
  'bio' : string,
  'name' : string,
  'joinedAt' : Timestamp,
  'avatarUrl' : [] | [string],
}
export type RequestId = bigint;
export type RequestStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface SaveProfileInput {
  'bio' : string,
  'name' : string,
  'avatarUrl' : [] | [string],
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = string;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptBookRequest' : ActorMethod<[string, RequestId], [] | [BookRequest]>,
  'addBook' : ActorMethod<[string, AddBookInput], Book>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'declineBookRequest' : ActorMethod<[string, RequestId], [] | [BookRequest]>,
  'deleteBook' : ActorMethod<[string, BookId], boolean>,
  'editBook' : ActorMethod<[string, BookId, EditBookInput], [] | [Book]>,
  'getAllAvailableBooks' : ActorMethod<[], Array<BookWithOwner>>,
  'getBookDetail' : ActorMethod<[BookId], [] | [BookWithOwner]>,
  'getCallerUserProfile' : ActorMethod<[string], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[string, ChatId], Array<Message>>,
  'getMyBooks' : ActorMethod<[string], Array<Book>>,
  'getMyChatThreads' : ActorMethod<[string], Array<ChatThread>>,
  'getMyRequestInbox' : ActorMethod<[string], Array<BookRequest>>,
  'getMyRequests' : ActorMethod<[string], Array<BookRequest>>,
  'getOrCreateChatThread' : ActorMethod<[string, RequestId], ChatThread>,
  'getSession' : ActorMethod<[string], [] | [UserId]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], AuthResult>,
  'register' : ActorMethod<[string, string], AuthResult>,
  'saveCallerUserProfile' : ActorMethod<[string, SaveProfileInput], undefined>,
  'searchBooks' : ActorMethod<[string], Array<BookWithOwner>>,
  'searchGoogleBooks' : ActorMethod<
    [string],
    { 'ok' : Array<GoogleBookResult> } |
      { 'err' : string }
  >,
  'sendBookRequest' : ActorMethod<[string, BookId], BookRequest>,
  'sendMessage' : ActorMethod<[string, ChatId, string], Message>,
  'setBookAvailability' : ActorMethod<
    [string, BookId, AvailabilityStatus],
    [] | [Book]
  >,
  'signOut' : ActorMethod<[string], undefined>,
  'transformGoogleBooksResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];