/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Profile {
    id: UserId;
    bio: string;
    name: string;
    joinedAt: Timestamp;
    avatarUrl?: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BookWithOwner {
    ownerName: string;
    book: Book;
}
export interface ChatThread {
    id: ChatId;
    participant1: UserId;
    participant2: UserId;
    requestId: RequestId;
    createdAt: Timestamp;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type RequestId = bigint;
export type BookId = bigint;
export type AuthResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface SaveProfileInput {
    bio: string;
    name: string;
    avatarUrl?: string;
}
export interface AddBookInput {
    title: string;
    author: string;
    coverImage?: ExternalBlob;
    genre: string;
    condition: BookCondition;
}
export type ChatId = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Book {
    id: BookId;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    author: string;
    coverImage?: ExternalBlob;
    availability: AvailabilityStatus;
    genre: string;
    condition: BookCondition;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BookRequest {
    id: RequestId;
    status: RequestStatus;
    bookOwnerId: UserId;
    createdAt: Timestamp;
    bookId: BookId;
    updatedAt: Timestamp;
    requesterId: UserId;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = string;
export type MessageId = bigint;
export interface GoogleBookResult {
    id: string;
    title: string;
    thumbnail: string;
    publishedDate: string;
    isbn: string;
    publisher: string;
    description: string;
    authors: Array<string>;
    printType: string;
}
export interface Message {
    id: MessageId;
    text: string;
    sentAt: Timestamp;
    chatId: ChatId;
    senderId: UserId;
}
export interface EditBookInput {
    title: string;
    author: string;
    coverImage?: ExternalBlob;
    genre: string;
    condition: BookCondition;
}
export enum AvailabilityStatus {
    available = "available",
    unavailable = "unavailable"
}
export enum BookCondition {
    new_ = "new",
    fair = "fair",
    good = "good",
    poor = "poor"
}
export enum RequestStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptBookRequest(token: string, requestId: RequestId): Promise<BookRequest | null>;
    addBook(token: string, input: AddBookInput): Promise<Book>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    declineBookRequest(token: string, requestId: RequestId): Promise<BookRequest | null>;
    deleteBook(token: string, bookId: BookId): Promise<boolean>;
    editBook(token: string, bookId: BookId, input: EditBookInput): Promise<Book | null>;
    getAllAvailableBooks(): Promise<Array<BookWithOwner>>;
    getBookDetail(bookId: BookId): Promise<BookWithOwner | null>;
    getCallerUserProfile(token: string): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatMessages(token: string, chatId: ChatId): Promise<Array<Message>>;
    getMyBooks(token: string): Promise<Array<Book>>;
    getMyChatThreads(token: string): Promise<Array<ChatThread>>;
    getMyRequestInbox(token: string): Promise<Array<BookRequest>>;
    getMyRequests(token: string): Promise<Array<BookRequest>>;
    getOrCreateChatThread(token: string, requestId: RequestId): Promise<ChatThread>;
    getSession(token: string): Promise<UserId | null>;
    getUserProfile(userId: UserId): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    login(email: string, password: string): Promise<AuthResult>;
    register(email: string, password: string): Promise<AuthResult>;
    saveCallerUserProfile(token: string, input: SaveProfileInput): Promise<void>;
    searchBooks(searchTerm: string): Promise<Array<BookWithOwner>>;
    searchGoogleBooks(searchQuery: string): Promise<{
        __kind__: "ok";
        ok: Array<GoogleBookResult>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendBookRequest(token: string, bookId: BookId): Promise<BookRequest>;
    sendMessage(token: string, chatId: ChatId, text: string): Promise<Message>;
    setBookAvailability(token: string, bookId: BookId, status: AvailabilityStatus): Promise<Book | null>;
    signOut(token: string): Promise<void>;
    transformGoogleBooksResponse(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AddBookInput as _AddBookInput, AuthResult as _AuthResult, AvailabilityStatus as _AvailabilityStatus, Book as _Book, BookCondition as _BookCondition, BookId as _BookId, BookRequest as _BookRequest, BookWithOwner as _BookWithOwner, EditBookInput as _EditBookInput, ExternalBlob as _ExternalBlob, GoogleBookResult as _GoogleBookResult, Profile as _Profile, RequestId as _RequestId, RequestStatus as _RequestStatus, SaveProfileInput as _SaveProfileInput, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptBookRequest(arg0: string, arg1: RequestId): Promise<BookRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptBookRequest(arg0, arg1);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptBookRequest(arg0, arg1);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addBook(arg0: string, arg1: AddBookInput): Promise<Book> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(arg0, await to_candid_AddBookInput_n13(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Book_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(arg0, await to_candid_AddBookInput_n13(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Book_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async declineBookRequest(arg0: string, arg1: RequestId): Promise<BookRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.declineBookRequest(arg0, arg1);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineBookRequest(arg0, arg1);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBook(arg0: string, arg1: BookId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0, arg1);
            return result;
        }
    }
    async editBook(arg0: string, arg1: BookId, arg2: EditBookInput): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.editBook(arg0, arg1, await to_candid_EditBookInput_n28(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBook(arg0, arg1, await to_candid_EditBookInput_n28(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAvailableBooks(): Promise<Array<BookWithOwner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvailableBooks();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvailableBooks();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookDetail(arg0: BookId): Promise<BookWithOwner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookDetail(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookDetail(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(arg0: string): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: string, arg1: ChatId): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0, arg1);
            return result;
        }
    }
    async getMyBooks(arg0: string): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBooks(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBooks(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyChatThreads(arg0: string): Promise<Array<ChatThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyChatThreads(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyChatThreads(arg0);
            return result;
        }
    }
    async getMyRequestInbox(arg0: string): Promise<Array<BookRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRequestInbox(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRequestInbox(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRequests(arg0: string): Promise<Array<BookRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRequests(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRequests(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateChatThread(arg0: string, arg1: RequestId): Promise<ChatThread> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateChatThread(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateChatThread(arg0, arg1);
            return result;
        }
    }
    async getSession(arg0: string): Promise<UserId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_AuthResult_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_AuthResult_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_AuthResult_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_AuthResult_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: SaveProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, to_candid_SaveProfileInput_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, to_candid_SaveProfileInput_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async searchBooks(arg0: string): Promise<Array<BookWithOwner>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBooks(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBooks(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchGoogleBooks(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<GoogleBookResult>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGoogleBooks(arg0);
                return from_candid_variant_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGoogleBooks(arg0);
            return from_candid_variant_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendBookRequest(arg0: string, arg1: BookId): Promise<BookRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBookRequest(arg0, arg1);
                return from_candid_BookRequest_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBookRequest(arg0, arg1);
            return from_candid_BookRequest_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string, arg1: ChatId, arg2: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setBookAvailability(arg0: string, arg1: BookId, arg2: AvailabilityStatus): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setBookAvailability(arg0, arg1, to_candid_AvailabilityStatus_n48(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBookAvailability(arg0, arg1, to_candid_AvailabilityStatus_n48(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async signOut(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signOut(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signOut(arg0);
            return result;
        }
    }
    async transformGoogleBooksResponse(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformGoogleBooksResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformGoogleBooksResponse(arg0);
            return result;
        }
    }
}
function from_candid_AuthResult_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_AvailabilityStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityStatus): AvailabilityStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_BookCondition_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookCondition): BookCondition {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_BookRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookRequest): BookRequest {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_BookWithOwner_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookWithOwner): Promise<BookWithOwner> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Book_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Promise<Book> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Profile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Book]): Promise<Book | null> {
    return value.length === 0 ? null : await from_candid_Book_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookWithOwner]): Promise<BookWithOwner | null> {
    return value.length === 0 ? null : await from_candid_BookWithOwner_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookRequest]): BookRequest | null {
    return value.length === 0 ? null : from_candid_BookRequest_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RequestId;
    status: _RequestStatus;
    bookOwnerId: _UserId;
    createdAt: _Timestamp;
    bookId: _BookId;
    updatedAt: _Timestamp;
    requesterId: _UserId;
}): {
    id: RequestId;
    status: RequestStatus;
    bookOwnerId: UserId;
    createdAt: Timestamp;
    bookId: BookId;
    updatedAt: Timestamp;
    requesterId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n11(_uploadFile, _downloadFile, value.status),
        bookOwnerId: value.bookOwnerId,
        createdAt: value.createdAt,
        bookId: value.bookId,
        updatedAt: value.updatedAt,
        requesterId: value.requesterId
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookId;
    title: string;
    owner: _UserId;
    createdAt: _Timestamp;
    author: string;
    coverImage: [] | [_ExternalBlob];
    availability: _AvailabilityStatus;
    genre: string;
    condition: _BookCondition;
}): Promise<{
    id: BookId;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    author: string;
    coverImage?: ExternalBlob;
    availability: AvailabilityStatus;
    genre: string;
    condition: BookCondition;
}> {
    return {
        id: value.id,
        title: value.title,
        owner: value.owner,
        createdAt: value.createdAt,
        author: value.author,
        coverImage: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.coverImage)),
        availability: from_candid_AvailabilityStatus_n22(_uploadFile, _downloadFile, value.availability),
        genre: value.genre,
        condition: from_candid_BookCondition_n24(_uploadFile, _downloadFile, value.condition)
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ownerName: string;
    book: _Book;
}): Promise<{
    ownerName: string;
    book: Book;
}> {
    return {
        ownerName: value.ownerName,
        book: await from_candid_Book_n18(_uploadFile, _downloadFile, value.book)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    name: string;
    joinedAt: _Timestamp;
    avatarUrl: [] | [string];
}): {
    id: UserId;
    bio: string;
    name: string;
    joinedAt: Timestamp;
    avatarUrl?: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        joinedAt: value.joinedAt,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "accepted" in value ? RequestStatus.accepted : "declined" in value ? RequestStatus.declined : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: null;
} | {
    unavailable: null;
}): AvailabilityStatus {
    return "available" in value ? AvailabilityStatus.available : "unavailable" in value ? AvailabilityStatus.unavailable : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
}): BookCondition {
    return "new" in value ? BookCondition.new : "fair" in value ? BookCondition.fair : "good" in value ? BookCondition.good : "poor" in value ? BookCondition.poor : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_GoogleBookResult>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<GoogleBookResult>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookWithOwner>): Promise<Array<BookWithOwner>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BookWithOwner_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Book>): Promise<Array<Book>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Book_n18(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookRequest>): Array<BookRequest> {
    return value.map((x)=>from_candid_BookRequest_n9(_uploadFile, _downloadFile, x));
}
async function to_candid_AddBookInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddBookInput): Promise<_AddBookInput> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_AvailabilityStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): _AvailabilityStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_BookCondition_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookCondition): _BookCondition {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_EditBookInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EditBookInput): Promise<_EditBookInput> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SaveProfileInput_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileInput): _SaveProfileInput {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    author: string;
    coverImage?: ExternalBlob;
    genre: string;
    condition: BookCondition;
}): Promise<{
    title: string;
    author: string;
    coverImage: [] | [_ExternalBlob];
    genre: string;
    condition: _BookCondition;
}> {
    return {
        title: value.title,
        author: value.author,
        coverImage: value.coverImage ? candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.coverImage)) : candid_none(),
        genre: value.genre,
        condition: to_candid_BookCondition_n16(_uploadFile, _downloadFile, value.condition)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    name: string;
    avatarUrl?: string;
}): {
    bio: string;
    name: string;
    avatarUrl: [] | [string];
} {
    return {
        bio: value.bio,
        name: value.name,
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookCondition): {
    new: null;
} | {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} {
    return value == BookCondition.new ? {
        new_: null
    } : value == BookCondition.fair ? {
        fair: null
    } : value == BookCondition.good ? {
        good: null
    } : value == BookCondition.poor ? {
        poor: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): {
    available: null;
} | {
    unavailable: null;
} {
    return value == AvailabilityStatus.available ? {
        available: null
    } : value == AvailabilityStatus.unavailable ? {
        unavailable: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
